name: "Update readme with issues"
on:
  workflow_dispatch:
  issues:
      types: ['opened', 'edited', 'closed']
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: rewriteReadme
      uses: seed-of-apricot/issue-list-readme@v1.1.0      
